### ISSUE TITLE
Unable to connect to cassandra: unable to create session: unable to discover protocol version: authentication required 

### ISSUE THREAD

**Issue by Hashfyre** [orzhaha/cassandra-web#12]
Hi,

I have tried deploying cassandra-web to kubernetes and hook it up with bitnami-cassandra, but the app fails with the following error:
```
{"time":"2020-08-20T09:08:51.771615881Z","level":"INFO","prefix":"-","file":"main.go","line":"131","message":"Cofing 設定成功"}
{"time":"2020-08-20T09:08:51.819951735Z","level":"FATAL","prefix":"-","file":"main.go","line":"154","message":"gocql: unable to create session: unable to discover protocol version: authentication required (using \"org.apache.cassandra.auth.PasswordAuthenticator\")"}
```

My deployment manifest looks like:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cassandra-web
  name: cassandra-web
  namespace: pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cassandra-web
    spec:
      containers:
      - name: cassandra-web
        image: ipushc/cassandra-web:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: HOST_PORT
          value: ":80"
        - name: CASSANDRA_HOST
          value: cassandra.pipeline.svc.cluster.local # <- tried with cassandra-headless too
        - name: CASSANDRA_PORT
          value: "9042"
        - name: CASSANDRA_USERNAME
          value: cassandra
        - name: CASSANDRA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: cassandra-password
              name: cassandra
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
```
